# Generated by Django 6.0.5 on 2026-05-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custodian',
            fields=[
                ('custodian_id', models.AutoField(primary_key=True, serialize=False)),
                ('custodian_code', models.CharField(max_length=10)),
                ('custodian_name', models.CharField(max_length=100)),
                ('custodian_type', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('can_hold_assets', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
            ],
        ),
    ]
