# Generated by Django 6.0.5 on 2026-05-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '__first__'),
        ('custodian', '0001_initial'),
        ('department', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodian',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
        migrations.AddField(
            model_name='custodian',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
