# Generated by Django 6.0.5 on 2026-05-21 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_code', models.CharField(blank=True, max_length=20, null=True)),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_type', models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('FINANCE', 'Finance'), ('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('OPERATIONS', 'Operations')], default='OPERATIONS', max_length=100)),
                ('allow_assignment', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_dept', models.ForeignKey(blank=True, db_column='parent_dept_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='department.department')),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
